name: Docker Image

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
  pull_request:
  schedule:
    - cron: "0 12 1-7 * 3"

env:
  SHOULD_PUSH: ${{ github.repository_owner == 'fabiang' && github.ref == 'refs/heads/main' }}

jobs:
  docker-image-alpine:
    strategy:
      matrix:
        version:
          # Version 17
          - alpine: 3.24
            sqlcmd: "17.10.1.1-1"
            sqlcmd_minor: "17.10"
            sqlcmd_major: ""
            download_url_msodbc: "https://download.microsoft.com/download/607ebe2c-e17c-4c34-b367-10a75b83bef9/msodbcsql17_17.11.1.1-1_amd64.apk"
            download_url_mssql: "https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.10.1.1-1_amd64.apk"
            latest: false
          - alpine: 3.24
            sqlcmd: "17.11.1.1-1"
            sqlcmd_minor: "17.11"
            sqlcmd_major: "17"
            download_url_msodbc: "https://download.microsoft.com/download/607ebe2c-e17c-4c34-b367-10a75b83bef9/msodbcsql17_17.11.1.1-1_amd64.apk"
            download_url_mssql: "https://download.microsoft.com/download/aca0282f-6a67-49c0-ae08-887d59d16d1a/mssql-tools_17.11.1.1-1_amd64.apk"
            latest: false
          # Version 18
          - alpine: 3.24
            sqlcmd: "18.2.1.1-1"
            sqlcmd_minor: "18.2"
            sqlcmd_major: ""
            download_url_msodbc: "https://download.microsoft.com/download/1/f/f/1fffb537-26ab-4947-a46a-7a45c27f6f77/msodbcsql18_18.2.1.1-1_amd64.apk"
            download_url_mssql: "https://download.microsoft.com/download/1/f/f/1fffb537-26ab-4947-a46a-7a45c27f6f77/mssql-tools18_18.2.1.1-1_amd64.apk"
            latest: false
          - alpine: 3.24
            sqlcmd: "18.4.1.1-1"
            sqlcmd_minor: "18.4"
            sqlcmd_major: ""
            download_url_msodbc: "https://download.microsoft.com/download/7/6/d/76de322a-d860-4894-9945-f0cc5d6a45f8/msodbcsql18_18.4.1.1-1_amd64.apk"
            download_url_mssql: "https://download.microsoft.com/download/7/6/d/76de322a-d860-4894-9945-f0cc5d6a45f8/mssql-tools18_18.4.1.1-1_amd64.apk"
            latest: false
          - alpine: 3.24
            sqlcmd: "18.6.2.1-1"
            sqlcmd_minor: "18.6"
            sqlcmd_major: "18"
            download_url_msodbc: "https://download.microsoft.com/download/0b3d5518-b4a7-4a2b-afc7-7ee9e967f93c/msodbcsql18_18.6.2.1-1_amd64.apk"
            download_url_mssql: "https://download.microsoft.com/download/cad0d30f-b9b1-4765-a011-81d8a66c8b8d/mssql-tools18_18.6.2.1-1_amd64.apk"
            latest: true  # newest possible version available -> tag as latest alpine-latest

    env:
      IMAGE_NAME_FULL: "fabiang/sqlcmd:${{ matrix.version.sqlcmd }}"
      IMAGE_NAME_MINOR: "fabiang/sqlcmd:${{ matrix.version.sqlcmd_minor }}"
      IMAGE_NAME_MAJOR: "fabiang/sqlcmd:${{ matrix.version.sqlcmd_major }}"
      IMAGE_NAME_ALPINE_FULL: "fabiang/sqlcmd:${{ matrix.version.sqlcmd }}-alpine${{ matrix.version.alpine }}"
      IMAGE_NAME_ALPINE_MINOR: "fabiang/sqlcmd:${{ matrix.version.sqlcmd_minor }}-alpine${{ matrix.version.alpine }}"
      IMAGE_NAME_ALPINE_MAJOR: "fabiang/sqlcmd:${{ matrix.version.sqlcmd_major }}-alpine${{ matrix.version.alpine }}"
      IMAGE_LATEST: "fabiang/sqlcmd:latest"
      IMAGE_LATEST_ALPINE: "fabiang/sqlcmd:latest-alpine"
      IMAGE_LATEST_ALPINE_MINOR: "fabiang/sqlcmd:${{ matrix.version.sqlcmd_minor }}-alpine"
      IMAGE_LATEST_ALPINE_MAJOR: "fabiang/sqlcmd:${{ matrix.version.sqlcmd_major }}-alpine"

    runs-on: ubuntu-latest

    name: "Sqlcmd v${{ matrix.version.sqlcmd }} (Alpine ${{ matrix.version.alpine }})"

    steps:
      - uses: actions/checkout@v6

      - name: SQLServer Checksum
        id: sqlserver-checksum
        shell: bash
        run: |
          echo "checksum=$(curl --silent -L --header 'Accept: application/vnd.docker.distribution.manifest.v2+json' 'https://mcr.microsoft.com/v2/mssql/server/manifests/2025-latest' | jq -r '.config.digest')" >> $GITHUB_OUTPUT

      - name: Cache Docker Image
        id: docker-image-cache
        uses: actions/cache@v6
        with:
          path: '*.tar'
          key: docker-image-cache-${{ runner.os }}-${{ steps.sqlserver-checksum.outputs.checksum }}

      - name: Load SQLServer image
        if: steps.docker-image-cache.outputs.cache-hit == 'true'
        run: docker image load -i sqlserver.tar

      - name: Run SQL Server
        run: |
          docker run \
            --pull always \
            -e 'ACCEPT_EULA=Y' \
            -e 'MSSQL_SA_PASSWORD=yourStrong(!)Password' \
            -p 1433:1433 \
            -d \
            --name SQLServer \
            --rm \
            mcr.microsoft.com/mssql/server:2025-latest

      - name: Wait for SQLServer to become available
        uses: iFaxity/wait-on-action@v1.2.1
        with:
          resource: tcp:localhost:1433
          timeout: 1800000
          interval: 5000
          log: true

      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '60' # for 60 seconds

      - name: Save SQLServer image
        if: steps.docker-image-cache.outputs.cache-hit != 'true'
        run: docker image save -o sqlserver.tar mcr.microsoft.com/mssql/server:2025-latest

      - name: Build Image
        run: |
          docker build -f alpine/Dockerfile \
            -t '${{ env.IMAGE_NAME_FULL }}' \
            -t '${{ env.IMAGE_NAME_ALPINE_FULL }}' \
            '--build-arg=ALPINE_VERSION=${{ matrix.version.alpine }}' \
            '--build-arg=MICROSOFT_DOWNLOAD_URL_MSODBC=${{ matrix.version.download_url_msodbc }}' \
            '--build-arg=MICROSOFT_DOWNLOAD_URL_TOOLS=${{ matrix.version.download_url_mssql }}' \
            .

      - name: Test image
        run: |
          docker run -t --rm --entrypoint='' --network=host \
            '${{ env.IMAGE_NAME_FULL }}' \
            sqlcmd -b -C -S 127.0.0.1,1433 -U sa -P 'yourStrong(!)Password' -Q 'SELECT @@VERSION'

      - name: Stop SQLServer
        if: always()
        run: docker stop SQLServer

      - name: Tag Minor
        if: "${{ matrix.version.sqlcmd_minor != '' }}"
        run: |
          docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MINOR }}'
          docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_ALPINE_MINOR }}'
          docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_LATEST_ALPINE_MINOR }}'

      - name: Tag Major
        if: "${{ matrix.version.sqlcmd_major != '' }}"
        run: |
          docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MAJOR }}'
          docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_ALPINE_MAJOR }}'
          docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_LATEST_ALPINE_MAJOR }}'

      - name: Tag Latest
        if: "${{ matrix.version.latest == true }}"
        run: |
          docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_LATEST }}'
          docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_LATEST_ALPINE }}'

      - name: Docker Hub login
        if: ${{ env.SHOULD_PUSH == 'true' }}
        uses: azure/docker-login@v2
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Push Image
        if: ${{ env.SHOULD_PUSH == 'true' }}
        run: |
          docker push '${{ env.IMAGE_NAME_FULL }}'
          docker push '${{ env.IMAGE_NAME_ALPINE_FULL }}'

      - name: Push Image Minor
        if: ${{ env.SHOULD_PUSH == 'true' && matrix.version.sqlcmd_minor != '' }}
        run: |
          docker push '${{ env.IMAGE_NAME_MINOR }}'
          docker push '${{ env.IMAGE_NAME_ALPINE_MINOR }}'
          docker push '${{ env.IMAGE_LATEST_ALPINE_MINOR }}'

      - name: Push Image Major
        if: ${{ env.SHOULD_PUSH == 'true' && matrix.version.sqlcmd_major != '' }}
        run: |
          docker push '${{ env.IMAGE_NAME_MAJOR }}'
          docker push '${{ env.IMAGE_NAME_ALPINE_MAJOR }}'
          docker push '${{ env.IMAGE_LATEST_ALPINE_MAJOR }}'

      - name: Push Lastest
        if: ${{ env.SHOULD_PUSH == 'true' && matrix.version.latest == true }}
        run: |
          docker push '${{ env.IMAGE_LATEST }}'
          docker push '${{ env.IMAGE_LATEST_ALPINE }}'
